APP HOMEWORK APRIL 29TH/mac/config/routes.rb
Rails.application.routes.draw do
  resources :gemstones
  resources :posts

   root 'posts#index'

end

APP HOMEWORK APRIL 29TH/mac/app/models/gemstone.rb
class Gemstone < ActiveRecord::Base
end

APP HOMEWORK APRIL 29TH/mac/app/models/post.rb
class Post < ActiveRecord::Base
end

APP HOMEWORK APRIL 29TH/mac/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

APP HOMEWORK APRIL 29TH/mac/app/controllers/gemstones_controller.rb
class GemstonesController < ApplicationController
  before_action :set_gemstone, only: [:show, :edit, :update, :destroy]

  # GET /gemstones
  # GET /gemstones.json
  def index
    @gemstones = Gemstone.all
  end

  # GET /gemstones/1
  # GET /gemstones/1.json
  def show
  end

  # GET /gemstones/new
  def new
    @gemstone = Gemstone.new
  end

  # GET /gemstones/1/edit
  def edit
  end

  # POST /gemstones
  # POST /gemstones.json
  def create
    @gemstone = Gemstone.new(gemstone_params)

    respond_to do |format|
      if @gemstone.save
        format.html { redirect_to @gemstone, notice: 'Gemstone was successfully created.' }
        format.json { render :show, status: :created, location: @gemstone }
      else
        format.html { render :new }
        format.json { render json: @gemstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gemstones/1
  # PATCH/PUT /gemstones/1.json
  def update
    respond_to do |format|
      if @gemstone.update(gemstone_params)
        format.html { redirect_to @gemstone, notice: 'Gemstone was successfully updated.' }
        format.json { render :show, status: :ok, location: @gemstone }
      else
        format.html { render :edit }
        format.json { render json: @gemstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gemstones/1
  # DELETE /gemstones/1.json
  def destroy
    @gemstone.destroy
    respond_to do |format|
      format.html { redirect_to gemstones_url, notice: 'Gemstone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gemstone
      @gemstone = Gemstone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gemstone_params
      params.require(:gemstone).permit(:name, :properties, :picture, :tag)
    end
end

APP HOMEWORK APRIL 29TH/mac/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
  @posts = Post.all.sample(1)
  @gemstones = Gemstone.all.sample(1)
 #  @posts = Post.all
 #    @posts = Post.all.to_a.shuffle
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
       @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:quote, :author, :tag)
    end
end

APP HOMEWORK APRIL 29TH/mac/app/helpers/application_helper.rb
module ApplicationHelper
end

APP HOMEWORK APRIL 29TH/mac/app/helpers/gemstones_helper.rb
module GemstonesHelper
end

APP HOMEWORK APRIL 29TH/mac/app/helpers/posts_helper.rb
module PostsHelper
end

APP HOMEWORK APRIL 29TH/mac/app/views/gemstones/_form.html.erb
<%= form_for(@gemstone) do |f| %>
  <% if @gemstone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gemstone.errors.count, "error") %> prohibited this gemstone from being saved:</h2>

      <ul>
      <% @gemstone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_area :properties %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

APP HOMEWORK APRIL 29TH/mac/app/views/gemstones/edit.html.erb
<h1>Editing Gemstone</h1>

<%= render 'form' %>

<%= link_to 'Show', @gemstone %> |
<%= link_to 'Back', gemstones_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/gemstones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gemstones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Properties</th>
      <th>Picture</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gemstones.each do |gemstone| %>
      <tr>
        <td><%= gemstone.name %></td>
        <td><%= gemstone.properties %></td>
        <td><%= gemstone.picture %></td>
        <td><%= gemstone.tag %></td>
        <td><%= link_to 'Edit', edit_gemstone_path(gemstone) %></td>
        <td><%= link_to 'Destroy', gemstone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gemstone', new_gemstone_path %>
<%= link_to 'Back', posts_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/gemstones/new.html.erb
<h1>New Gemstone</h1>

<%= render 'form' %>

<%= link_to 'Back', gemstones_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/gemstones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gemstone.name %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @gemstone.properties %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @gemstone.picture %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @gemstone.tag %>
</p>

<%= link_to 'Edit', edit_gemstone_path(@gemstone) %> |
<%= link_to 'Back', gemstones_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

APP HOMEWORK APRIL 29TH/mac/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

APP HOMEWORK APRIL 29TH/mac/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to the "Quote & Gemstone Shuffler"!</h1>
Click shuffle to discover an inspirational quote together with a gemstone. 

    <% @posts.each do |post| %>
    <br><br>
      <b>  <%= post.quote %> </b>
        <br>
  <%= post.author %>. Tags:
  <i><%= post.tag %></i>
   <% end %>

<% @gemstones.each do |gemstone| %>
    <br><br>
      <b>  <%= gemstone.name %> </b>
        <br>
  <%= gemstone.properties %> Tags:
  <i><%= gemstone.tag %></i>
   <br>
  <%= gemstone.picture %>
   <% end %>
<br>

<br><%= link_to 'Shuffle', posts_path %>
<br>
<%= link_to 'Show all Quotes', url_for('/posts/1') %>
<br>
<%= link_to 'Show all Gemstones', url_for('/gemstones') %>
<br>
<br>
This app has been created to promote inspiration with quotes and boost your knowledge on gemstones.

APP HOMEWORK APRIL 29TH/mac/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

APP HOMEWORK APRIL 29TH/mac/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Quotes</h1>
<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr><br>
        <% @posts.each do |post| %>
        <td><%= post.quote %></td>
        <td><%= post.author %></td>
        <td><%= post.tag %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Back', posts_path %>